### PR TITLE
Added actual files i forgot to stage

### PR DESCRIPTION
**Pull request by klein1992**

### CODE REVIEW

**Comment by AleksandrHovhannisyan** [comment]
Looks good, but I'm not sure how this'll work with the floor setup we have now.

**Comment by klein1992** [comment]
There is no way to place a trap door prefab or some object on an existing floor and have the area where you place the trap door or object "disappear" so that the trap door opens. I'm not sure if you understand what I mean. Basically I can't selectively eliminate a portion of an existing mesh. I recommend using this in a corner. It can be placed anywhere tho. A new "floor" with trap door should be created.

**Comment by AleksandrHovhannisyan** [comment]
We could honestly just create a special room prefab that's a boss room, with a hole for where the trap door would go :)

**Review by Jazy5552 — APPROVED** [review]
👌

**Pull request merged**
