### PR TITLE
Feature/random spawns

### PR DESCRIPTION
**Pull request by AleksandrHovhannisyan**
#140 

Not sure how much better this makes things. Let me know what you guys think. I'm sorta indifferent about it.

### CODE REVIEW

**Review by CameroonD — COMMENTED** [review]
Getting an argument out of range exception occasionally which causes enemies to not spawn.

**Comment by CameroonD** [comment]
This seems to break the boss as well

**Comment by CameroonD** [comment]
I'm not sure that I like the idea of them having the same probability of spawning. Some enemies are harder than others. Hard rooms should be more likely to spawn harder enemies.

**Comment by CameroonD** [comment]
Doors in boss room remaining open. Might have something to do with the way the door system keeps track of the enemies in the room.

**Comment by AleksandrHovhannisyan** [comment]
Not sure what to tell ya. I just tested this and the boss doors close.

**Review by CameroonD — APPROVED** [review]
Can't reproduce that. Probably was just a local issue ¯\\_(ツ)_/¯

**Pull request merged**
