### PR TITLE
M1 Vertical Slice Milestone

### PR DESCRIPTION
**Pull request by AleksandrHovhannisyan**

### CODE REVIEW

**Review by klein1992 — DISMISSED** [review]
240K damn. Good job!

**Review by CameroonD — DISMISSED** [review]
Looks great! Controller support works exactly as intended. Found a couple of small issues. When you beat the game it doesn't seem that there's any way to quit. Since this is just one level, we may want to drop the player back at the main menu for now. Also, the main menu seems tiny to me. I would like to see it resize to fill more of the screen.

**Review by klein1992 — APPROVED** [review]
Beautiful

**Review by CameroonD — APPROVED** [review]
Looks good to me. My concerns have been answered, the two fixes I requested work. 👍

**Pull request merged**
